overrides:
  "@webext-core/isolated-element": 1.1.4
  brace-expansion@1: 1.1.13
  brace-expansion@5: 5.0.6
  defu: 6.1.5
  node-forge: 1.4.0
  picomatch@2: 2.3.2
  picomatch@4: 4.0.4
  postcss: 8.5.10
  shell-quote: 1.8.4
  tmp: 0.2.7
  uuid: 11.1.1
  yaml@1: 1.10.3
  yaml@2: 2.8.3
